# Generated by Django 2.2 on 2021-10-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0008_doctors_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurses',
            name='age',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
