# Generated by Django 2.2 on 2021-10-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0009_nurses_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
