# Generated by Django 2.2 on 2021-10-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0010_patients_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurses',
            name='assigned_doctor',
        ),
    ]
