# Generated by Django 2.2 on 2021-10-10 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0011_remove_nurses_assigned_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurses',
            name='assigned_doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='managements.Doctors'),
        ),
    ]
