# Generated by Django 2.2 on 2021-10-10 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0013_auto_20211010_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurses',
            name='assigned_doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='managements.Doctors'),
        ),
    ]
