# Generated by Django 2.2 on 2021-10-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0014_auto_20211010_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Others')], default=3, max_length=1),
        ),
    ]
