# Generated by Django 2.2 on 2021-10-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0015_auto_20211011_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Others')]),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Others')]),
        ),
    ]
