# Generated by Django 2.2 on 2021-10-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0016_auto_20211011_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Others')]),
        ),
    ]
