# Generated by Django 2.2 on 2021-10-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0018_auto_20211011_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1, max_length=6),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')]),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')]),
        ),
    ]
