# Generated by Django 2.2 on 2021-10-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0019_auto_20211011_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[(1, 'male'), (2, 'female'), (3, 'other')], default=1, max_length=6),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='gender',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')]),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')]),
        ),
    ]
