# Generated by Django 2.2 on 2021-10-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0020_auto_20211011_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default=1, max_length=6),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='gender',
            field=models.IntegerField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')]),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.IntegerField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')]),
        ),
    ]
