# Generated by Django 2.2 on 2021-10-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0021_auto_20211011_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default=1, max_length=1),
        ),
    ]
