# Generated by Django 2.2 on 2021-10-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0022_auto_20211011_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[('M/m', 'male'), ('F/f', 'female'), ('O/o', 'other')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='gender',
            field=models.IntegerField(choices=[('M/m', 'male'), ('F/f', 'female'), ('O/o', 'other')]),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.IntegerField(choices=[('M/m', 'male'), ('F/f', 'female'), ('O/o', 'other')]),
        ),
    ]
