# Generated by Django 2.2 on 2021-10-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0023_auto_20211011_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='gender',
            field=models.IntegerField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')]),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.IntegerField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')]),
        ),
    ]
