# Generated by Django 2.2 on 2021-10-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0027_auto_20211011_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='nurses',
            options={'verbose_name_plural': 'Nurses'},
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name_plural': 'Patients'},
        ),
        migrations.RenameField(
            model_name='nurses',
            old_name='assigned_doctor',
            new_name='doctor',
        ),
    ]
