# Generated by Django 2.2 on 2021-10-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0028_auto_20211012_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurses',
            old_name='doctor',
            new_name='doctors',
        ),
    ]
