# Generated by Django 2.2 on 2021-10-12 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0029_auto_20211012_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurses',
            name='doctors',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='managements.Doctors'),
        ),
    ]
