# Generated by Django 2.2 on 2021-10-12 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0030_auto_20211012_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurses',
            name='doctors',
        ),
        migrations.AddField(
            model_name='nurses',
            name='assigned_doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='managements.Doctors'),
        ),
    ]
