# Generated by Django 2.2 on 2021-10-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0035_auto_20211012_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurses',
            old_name='assigned_doctor',
            new_name='doctors',
        ),
    ]
