# Generated by Django 2.2 on 2021-10-12 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0036_auto_20211012_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurses',
            name='doctors',
        ),
    ]
