# Generated by Django 2.2 on 2021-10-12 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0037_remove_nurses_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurses',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='managements.Doctors'),
        ),
    ]
