# Generated by Django 2.2 on 2021-10-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0039_auto_20211012_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nurses',
            options={'verbose_name_plural': 'Patients'},
        ),
        migrations.RemoveField(
            model_name='nurses',
            name='doctors',
        ),
        migrations.AddField(
            model_name='nurses',
            name='doctor',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
