# Generated by Django 2.2 on 2021-10-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0040_auto_20211012_1354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nurses',
            new_name='Nurse',
        ),
    ]
