# Generated by Django 2.2 on 2021-10-13 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0046_auto_20211013_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nurses',
            options={'verbose_name_plural': 'Nurses'},
        ),
        migrations.AlterField(
            model_name='nurses',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses', to='managements.Doctors'),
        ),
    ]
