# Generated by Django 2.2 on 2021-10-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0047_auto_20211013_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurses',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.Doctors'),
        ),
    ]
