# Generated by Django 2.2 on 2021-10-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0048_auto_20211013_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurses',
            name='doctor',
        ),
        migrations.AddField(
            model_name='nurses',
            name='doctor',
            field=models.ManyToManyField(blank=True, to='managements.Doctors'),
        ),
    ]
