# Generated by Django 2.2 on 2021-10-13 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0049_auto_20211013_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurses',
            name='doctor',
        ),
        migrations.AddField(
            model_name='nurses',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='managements.Doctors'),
        ),
    ]
