# Generated by Django 2.2 on 2021-10-19 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0041_auto_20211012_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='doctor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='managements.Doctors'),
        ),
    ]
