# Generated by Django 2.2 on 2021-10-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210924_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'doctor'), (2, 'patient'), (3, 'HR'), (4, 'Receptionist')], default=2),
        ),
    ]
